export const GET_JOBS = 'GET_JOBS';
export const JOBS_LOADING = 'JOBS_LOADING';

export const GET_CATEGORY_JOBS = 'GET_CATEGORY_JOBS';
export const GET_CATEGORY_JOBS_FAIL = 'GET_CATEGORY_JOBS_FAIL';

export const GET_SUB_CATEGORY_JOBS = 'GET_SUB_CATEGORY_JOBS';
export const GET_SUB_CATEGORY_JOBS_FAIL = 'GET_SUB_CATEGORY_JOBS_FAIL';

export const GET_ACTIVE_JOBS = 'GET_ACTIVE_JOBS';
export const GET_ACTIVE_JOBS_FAIL = 'GET_ACTIVE_JOBS_FAIL';

export const GET_ARCHIVED_JOBS = 'GET_ARCHIVED_JOBS';
export const GET_ARCHIVED_JOBS_FAIL = 'GET_ARCHIVED_JOBS_FAIL';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL';
