export const SUBSCRIBETONEWSLETTER = 'SUBSCRIBETONEWSLETTER';
export const SUBSCRIBE_FAIL = 'SUBSCRIBE_FAIL';

export const GET_SUBSCRIBERS = 'GET_SUBSCRIBERS';
export const SUBSCRIBERS_LOADING = 'SUBSCRIBERS_LOADING';
export const GET_SUBSCRIBER = 'GET_SUBSCRIBER';

export const DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER';
export const DELETE_SUBSCRIBER_FAIL = 'DELETE_SUBSCRIBER_FAIL';